*Create an Enduring dataset;
Data SCF.SCFSynth;
	set SCFSynth;
	if Occat1=2 then SelfEmployed=1;
	else SelfEmployed=0;
	If Occat2=1 then ManageProf=1;
	else ManageProf=0;
run;

*1. Average wealth of the 1% by ethnicity.;
	*Create Wealth cutoff variables;
	proc sort data=SCF.SCFSynth;
		by year;
	run;
	Proc Means P99 Data=SCF.SCFSynth;
		Var NetWorth;
		by year;
		Weight wgt; 
		output 	out = Networth99 P99=Networth99v;
	run;
	Proc Means P95 Data=SCF.SCFSynth;
		Var Networth;
		by year;
		Weight wgt; 
		output 	out = Networth95 P95=Networth95v;
	run;
	Proc Means P90 Data=SCF.SCFSynth;
		Var Networth;
		by year;
		Weight wgt; 
		output 	out = Networth90 P90=Networth90v;
	run;
	*Merge wealth cutoffs into SCF.SCFSynth;
	DATA SCF.SCFSynth;
		merge SCF.SCFSynth Networth90 Networth95 Networth99;
		by year;
	run;
	*Create percentile labels;
	DATA SCF.SCFSynth;
		set SCF.SCFSynth;
		if NetWorth>Networth99v then Percent1=1; else Percent1=0;
		if NetWorth>Networth95v then Percent5=1; else Percent5=0;
		if NetWorth>Networth90v then Percent10=1; else Percent10=0;
	run;
	*Sort by Ethnicity1;
	proc sort data=SCF.SCFSynth;
		by Ethnicity1;
	run;
	*Stats;
	proc means;
		var Networth;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
*2. Ethnicity composition of the 1%, 5%, and 10% over time.;
	proc sort data=SCF.SCFSynth;
		by year;
	run;

	proc freq data=SCF.SCFSynth;
		tables Ethnicity1; 
		where Percent1=1;
		Weight wgt;
		by year;
	run;

	proc freq data=SCF.SCFSynth;
		tables Ethnicity1; 
		where Percent5=1;
		Weight wgt;
		by year;
	run;

	proc freq data=SCF.SCFSynth;
		tables Ethnicity1; 
		where Percent10=1;
		Weight wgt;
	run;


*3. Frequency of investments in business of the 1% by ethnicity.;
	*Sort by Ethnicity1;
	proc sort data=SCF.SCFSynth;
		by Ethnicity1;
	run;
	*Create variable to see rate of investment;
	data SCF.SCFSynth;
		set SCF.SCFSynth;
		if BusinessValue>0 & BusinessValue~=. then InvestInBusiness=1; else InvestInBusiness=0;
	run;
	*Invest;
	proc means;
		var InvestInBusiness;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
	*Value;
	proc means;
		var BusinessValue;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;


*4. Correlation of high-risk investment and 1% status by ethnicity.;
	*create needed variables;
	data SCF.SCFSynth;
		set SCF.SCFSynth;
		if LifeInsuranceValue>0 & LifeInsuranceValue~=. then OwnLifeInsurance=1; else OwnLifeInsurance=0;
		if StockMutual=1 | InterestBank=1 | Checking=1 | IRAor401k=1 | OwnLifeInsurance=1 | AnyFinancialAssets=1 then AnyFinancialAssets=1; else AnyFinancialAssets=0;
	run;
	*ownership;
	proc means;
		var StockMutual InterestBank Nochk IRAor401k OwnLifeInsurance AnyFinancialAssets;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
	*Values;
	proc means;
		var StockValue mma IraValue LifeInsuranceValue;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
	*Values for those with any;
	proc means;
		var StockValue;
		by Ethnicity1;
		where Percent1=1 & StockValue>0;
		Weight wgt;
	run;
	proc means;
		var mma;
		by Ethnicity1;
		where Percent1=1 & mma>0;
		Weight wgt;
	run;
	proc means;
		var IraValue ;
		by Ethnicity1;
		where Percent1=1 & IraValue>0;
		Weight wgt;
	run;
	proc means;
		var LifeInsuranceValue;
		by Ethnicity1;
		where Percent1=1 & LifeInsuranceValue>0;
		Weight wgt;
	run;
*Home Ownership;
proc means;
		var Homeowner;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
	proc means;
		var HomeEquity HomeDebt;
		by Ethnicity1;
		where Percent1=1 & Homeowner=1;
		Weight wgt;
	run;

*Marital, Children, Age; 
	proc means;
		var Married Children Age;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
*Education;
	proc means;
		var LessThanHS HSGraduate SomeCollege Bachelors AdvancedDegree;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;

*Self Employed, Managerial/Professional Occupation;
	proc means;
		var ManageProf SelfEmployed;
		by Ethnicity1;
		where Percent1=1;
		Weight wgt;
	run;
